[project]
name = "cvs-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "test", email = "test@test.com" }
]
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.1.4",
    "matplotlib>=3.11.1",
    "starlette<0.49",
    "streamlit>=1.61.1",
]

[project.scripts]
cvs-analysis = "cvs_analysis:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
